### ISSUE TITLE
Libs outdated

### ISSUE THREAD

**Issue by suppergerrie2** [Majic-Jungle/splugins#2]
The compiled libs in the libs folder are outdated, they've not been updated since the log functions were added. This makes CModding with logs harder as we need to compile them ourselves now. This is then made slightly harder as the projects are also not updated to contain the SPLog.h and SPLog.c files.

**Comment by mjdave** [comment]
Thanks, and sorry it took me so long to get to this. I've added a build step to copy them across, so they should be up to date with the current build from now on.
